### ISSUE TITLE
`verdi calcjob inputcat` does not work

### ISSUE THREAD

**Issue by danielhollas** [pzarabadip/aiida-orca#27]
`verdi calcjob inputcat <pk>` should print the orca input file, but I currently get:

```sh
Critical: "CalcJobNode" and its process class "OrcaCalculation" do not define a default input file (option "input_filename" not found).
Please specify a path explicitly.
```

Same is true for `verdi calcjob outputcat`, which should print the output file I think.

I'll try to fix that, but need to dig into to documentation a bit. Hopefully it's a straightforward change which is backwards compatible.

**Comment by danielhollas** [comment]
`verdi calcjob res <pk> has the same issue

**Comment by pzarabadip** [comment]
Thanks @danielhollas.
It should be fixed within #29 
I'll merge as soon as tests pass successfully.

**Comment by danielhollas** [comment]
Hehe, you're so fast. :D Today I basically just managed to configure aiida to launch jobs on our cluster. :sweat:

**Comment by ezpzbz** [comment]
This should be fixed now. I've merged this fix along with base for documentation as well as code with typing and docstrings to the `master`. It also contains fixes on GitHub Actions and `pymatgen`.
