### ISSUE TITLE
OrcaBaseParser should handle truncated ORCA output gracefully

### ISSUE THREAD

**Issue by danielhollas** [pzarabadip/aiida-orca#32]
When a user provides a bad input parameter for ORCA, OrcaBaseParser throws this unhelpful exception (and excepts the CalcJob)

```python
 | [952|OrcaCalculation|on_except]: Traceback (most recent call last):
 |   File "/opt/conda/lib/python3.8/site-packages/plumpy/process_states.py", line 231, in execute
 |     result = self.run_fn(*self.args, **self.kwargs)
 |   File "/opt/conda/lib/python3.8/site-packages/aiida/engine/processes/calcjobs/calcjob.py", line 388, in parse
 |     exit_code_retrieved = self.parse_retrieved_output(retrieved_temporary_folder)
 |   File "/opt/conda/lib/python3.8/site-packages/aiida/engine/processes/calcjobs/calcjob.py", line 468, in parse_retrieved_output
 |     exit_code = parser.parse(**parse_kwargs)
 |   File "/home/aiida/plugins/aiida-orca/aiida_orca/parsers/__init__.py", line 72, in parse
 |     keywords = output_dict['metadata']['keywords']
 | KeyError: 'keywords'
```

Instead, we should catch this case and return some non_zero exit code, which can then be acted upon in workflows.

I'll submit a PR once I learn more about parsers and their exit codes. Basically just need to add some error handling here:

https://github.com/pzarabadip/aiida-orca/blob/5b2cba2b518837c35179b52ac1141eda27609f4b/aiida_orca/parsers/__init__.py#L72

It would also be nice to pass the ORCA error to the process report, if that is possible.

Here's the example ORCA output (without headers) where this happens (note that cclib does not throw any errors, which is the problem).

```
 Your ORCA version has been built with support for libXC version: 5.1.0
 For citations please refer to: https://tddft.org/programs/libxc/

 This ORCA versions uses:
   CBLAS   interface :  Fast vector & matrix operations
   LAPACKE interface :  Fast linear algebra routines
   SCALAPACK package :  Parallel linear algebra routines
   Shared memory     :  Shared parallel matrices
   BLAS/LAPACK       :  OpenBLAS 0.3.15  USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell SINGLE_THREADED
        Core in use  :  Haswell
   Copyright (c) 2011-2014, The OpenBLAS Project

            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                                 INPUT ERROR
            UNRECOGNIZED OR DUPLICATED KEYWORD(S) IN SIMPLE INPUT LINE
              SVWN         
            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[file orca_main/maininp4.cpp, line 11063]: 

[file orca_main/maininp4.cpp, line 11063]: 
```

PS: I am now playing with aiida and aiida-orca and it generally works great! Thanks for writing this plugin @pzarabadip! :heart: 
PPS: I am now using a dev version of `cclib` (from their master) so that I can parse ORCA-5.0 outputs.

**Comment by ezpzbz** [comment]
Plugin in general needs to do even much more.
cclib parser provides warnings as one of the attributes.
Those can be translated into error handlers in the `BaseWorkChain`.

Addressing the #34 via #37 would remove calling for `keyword`. However, currently, there is no mechanism in place to throw a proper message if parser could not parse the output. Hopefully, I would address it at some point soon.

**Comment by danielhollas** [comment]
Just noticed that the output dict from cclib contains the keyword 'success' that we should definitely be checking.

**Comment by danielhollas** [comment]
> However, currently, there is no mechanism in place to throw a proper message if parser could not parse the output. Hopefully, I would address it at some point soon.

If I am not mistaken, you could add a new exit code in the `orca_main` Calcjob and return it, as you already do here?

https://github.com/pzarabadip/aiida-orca/blob/5b2cba2b518837c35179b52ac1141eda27609f4b/aiida_orca/calculations/orca_main.py#L58

https://github.com/pzarabadip/aiida-orca/blob/5b2cba2b518837c35179b52ac1141eda27609f4b/aiida_orca/parsers/__init__.py#L33

**Comment by ezpzbz** [comment]
It should be resolved now. Feel free to open another issue if this still happens.
