### ISSUE TITLE
relaxed_structure StructureData should preserve atom ordering

### ISSUE THREAD

**Issue by danielhollas** [pzarabadip/aiida-orca#33]
It seems that the output node `relaxed_structure` of optimization runs has a different atom order that the original input structure.
I need to do a bit more testing, but probably this line from the parser needs tweaking.

https://github.com/pzarabadip/aiida-orca/blob/5b2cba2b518837c35179b52ac1141eda27609f4b/aiida_orca/parsers/__init__.py#L86

**Comment by ezpzbz** [comment]
Hi @danielhollas 
Thanks a lot for submitting the issues. Sorry for radio silence. I will get back to submitted issues in late december. Certainly, PRs are highly welcome!
Cheers,
Pezhman

**Comment by danielhollas** [comment]
No worries! Yes, I am planning to submit PRs for these. I am just now focusing on prototyping my project. Once I am in the refactoring phase, I will come back. :-) Otherwise the plugin works great! These are all super-minor.

**Comment by ezpzbz** [comment]
Glad to hear it helps you and your research! Cheers!

**Comment by ezpzbz** [comment]
Once the #37 is merged, we can test it probably.
In general, it should not be changed but there is possibility that reading the structure using pymatgen does not result in same ordering? I doubt it though but we can confirm it later.

**Comment by ezpzbz** [comment]
Hi @danielhollas please provide an example which reproduces this issue which would help to debug (if there is any)

**Comment by danielhollas** [comment]
@pzarabadip sure, I'll have a look. Not sure where I saw this so it might take me some time, but this is not super urgent.

**Comment by ezpzbz** [comment]
No problem. I close the issue for now then.
