### ISSUE TITLE
Determine optimization run from CClib

### ISSUE THREAD

**Issue by danielhollas** [pzarabadip/aiida-orca#34]
The current approach of to determine whether structure optimization has been run is most probably not robust:

https://github.com/pzarabadip/aiida-orca/blob/5b2cba2b518837c35179b52ac1141eda27609f4b/aiida_orca/parsers/__init__.py#L79

We're trying to detect the `Opt` keyword, but optimization can be triggered by other means as well. Instead we could try to use a  CClib field `output_dict['optdone']`. I need to test that first though.

**Comment by ezpzbz** [comment]
This is addressed in #37
