### ISSUE TITLE
Support AiiDA 2.0

### ISSUE THREAD

**Issue by danielhollas** [pzarabadip/aiida-orca#35]
AiiDA 2.0 has been released couple months ago. 

https://www.aiida.net/news/aiida-v2-0-0-released/

I haven't tested it yet with this plugin, but I plan to do it once they update the AiiDAlab image.

Here is the plugin migration guide.

https://github.com/aiidateam/aiida-core/wiki/AiiDA-2.0-plugin-migration-guide

**Comment by ezpzbz** [comment]
It would be nice to make the `aiida-orca` compatible with `AiiDA 2.0`.
My plan is to make the current implementation a bit more cleaner with proper support for `ORCA 5`. This will let me have a legacy branch to support `AiiDA <2`.
Then, I agree that the major development should be done once it is migrated to the `AiiDA 2.0`.

**Comment by danielhollas** [comment]
@pzarabadip Reposting info from Slack about AiiDA hackathon specifically about migrating to AiiDA 2.0. I will be there online.

> We are holding 2 days online + in-person (at EPFL Lausanne) mixed AiiDA plugin hackathon on the 21st/22nd of November (9am -5pm CET), focused on helping plugin developers migrate their plugins to support AiiDA 2.x and help improve the design of the plugins.The main goal of the hackathon will be focused in helping plugin developers in migrating their plugins to support AiiDA 2.x. Once that is achieved, some secondary objectives include:
To present the new features of aiida-core v2.x (including the upcoming v2.1 release)
> To discuss the general guidelines for plugin design.
> - To provide advice on how to write unit/CI tests for the plugin with newly added features.
> - To push to have all aiida-common-workflow supported simulation code running on the Quantum Mobile with the corresponding plugin.
> If you confirm to participate in the event, please feel the form: https://forms.gle/jH8fjBJWrp8HqdhJ7Do not hesitate to contact us directly with any questions you may have. On our part,
we will communicate back to the people interested with more information as soon as we have it.

**Comment by danielhollas** [comment]
This is now done :tada:  (although we need an official release)

**Comment by ezpzbz** [comment]
I'll make a release probably sometime during next weekend.
@danielhollas Let's have open PRs merged. I'll take care of `README`. I also need to do a bit of work on typing stuffs.

**Comment by danielhollas** [comment]
Release next week would be great, thanks! I need to focus on other things this week, but I'll try to finish the last PR during the weekend.

btw: For the release, I think it would be nice to have a CHANGELOG section in the docs that would document all the breaking changes between the last and new release, since there have been a bunch of them...
