### ISSUE TITLE
Switch setup.json to setup.cfg

### ISSUE THREAD

**Issue by danielhollas** [pzarabadip/aiida-orca#38]
We could look at the current output of [aiida plugin cookiecutter](https://github.com/aiidateam/aiida-plugin-cutter) for guidance.

@pzarabadip happy to take this on in case it would help.

**Comment by danielhollas** [comment]
This is PR from `aiida-core` is relevant https://github.com/aiidateam/aiida-core/pull/5312

**Comment by ezpzbz** [comment]
I'm already doing it but not with `setup.cfg`. I have it in another branch which I will push once #37 is merged.
