### ISSUE TITLE
Support for Orca 5

### ISSUE THREAD

**Issue by awvwgk** [pzarabadip/aiida-orca#58]
Currently the README states that Orca 5 is not supported. Is there any change from Orca 4 to 5 which is blocking or has the combination not been tested so far?

As far as I'm aware, there were changes in the defaults for most calculations as well as adding support for a full scripting language in the input files.

**Comment by danielhollas** [comment]
Hi @awvwgk ,

I am currently using this plugin with ORCA 5 and it works fine. We're using cclib for parsing the output so whatever cclib supports should work.

The new compound job scripting will probably not work since it uses slightly different syntax.

We'll need to update the readme.

**Comment by danielhollas** [comment]
README updated.
