### ISSUE TITLE
🧪 Update readme

### ISSUE THREAD

**Issue by ezpzbz** [pzarabadip/aiida-orca#59]
There has been a quite recent changes/improvements in the plugin. We need to update `README` to reflect such additions inclduing:

- [x] `AiiDA v2.0` support
- [x] `ORCA v5.0` support
- [x] Change coverage to the default branch (`develop`)
- [x] Remove heavy development disclaimer statement.
- [x] Update Acknowledgment
- [x] Add link to `aiida-common-workflows` paper as a use-case of the plugin
- [x] Update author lists

Anything else missing @danielhollas ?

**Comment by danielhollas** [comment]
Indeed :tada: 

I think you covered everything. I would add maybe also to update things in docs. For example the dev section is outdated now

https://aiida-orca.readthedocs.io/en/develop/developer_guide/index.html

Maybe the easiest thing would be to just link to the [Development section of the README](https://github.com/pzarabadip/aiida-orca#development) to avoid duplication.

**Comment by ezpzbz** [comment]
Agreed. 
I'd do it other way around. We can keep `README` short and simple and leave such stuffs to the documentation.

**Comment by ezpzbz** [comment]
I'm preparing to make a release soon @danielhollas. Just to make sure, I do not see any API incompatible changes, hence going with `0.6.0` version?

**Comment by danielhollas** [comment]
Yep, I'd go for 0.6 . We have a big disclaimer in readme, so until 1.0 is reached it is fine to break things in minor releases.

The only change I remember are the exit codes. It would be nice to have a changelog to document these.

**Comment by danielhollas** [comment]
@pzarabadip by the way, I just remember that the biggest breaking change was the change of entry points.
